using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Timestone.SnelStartClient.Models.Core;

/// <summary>
/// Represents the configured function of a general ledger.
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum GeneralLedgerFunctionModel
{
    Diversen,
    DagboekKas,
    DagboekBank,
    DagboekGiro,
    DagboekVerkoop,
    DagboekInkoop,
    DagboekMemoriaal,
    DagboekBalans,
    VerkopenOmzetOnbelastVerlegd,
    VerkopenOmzetLaag,
    VerkopenOmzetHoog,
    VerkopenOmzetOverig,
    VerkopenBtwVrij,
    BtwAfteDragenLaag,
    BtwAfTeDragenHoog,
    BtwAfTeDragenOverig,
    BtwAfTeDragenVerlegdVerkopen,
    BtwTeVorderenVerlegd,
    BtwAfteDragenLaagGlobalisatie,
    BtwAfTeDragenHoogGlobalisatie,
    BtwAfTeDragenOverigGlobalisatie,
    InkopenKostenAlleBtwTarieven,
    InkopenKostenLaag,
    InkopenKostenHoog,
    InkopenKostenOverig,
    InkopenVraagPosten,
    BtwTeVorderenLaag,
    BtwTeVorderenHoog,
    BtwTeVorderenOverig,
    BtwAfTeDragenVerlegdInkopen,
    BtwTeVorderenVerlegdInkopen,
    InkopenImportBinnenEUlaag,
    InkopenImportBinnenEUhoog,
    InkopenImportBinnenEUoverig,
    InkopenImportBuitenEUlaag,
    InkopenImportBuitenEUhoog,
    InkopenImportBuitenEUoverig,
    VerkopenExportBinnenEU,
    VerkopenExportBuitenEU,
    OninbareVorderingen,
    HerrekeningCorrecties,
    InstallatieTeleverkoopBinnenEUgeen,
    BpmVerkopen,
    BpmInkopen,
    BpmVoorraad,
    DienstverleningBinnenEU,
    VerkoopGlobalisatieLaag,
    VerkoopGlobalisatieHoog,
    VerkoopGlobalisatieOverig,
    InkoopGlobalisatieLaag,
    InkoopGlobalisatieHoog,
    InkoopGlobalisatieOverig,
    BtwGlobalisatie,
    KredietbeperkingVerkopen,
    KredietbeperkingInkopen,
    Betalingskorting,
    TussenrekeningBetalingen,
    OnbekendeBetalingen,
    Kruisposten,
    ContanteBetaling,
    ElectronischeBetaling,
    Winstboeking,
}
